// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

/* eslint-disable */
import type { BaseTranslation as BaseTranslationType } from 'typesafe-i18n'
import type { LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales = 'en' | 'fr'

export type Translation = {
  home: {
    /**
     * My new app
     */
    title: string
  }
  common: {
    seo: {
      /**
       * This is my new app
       */
      description: string
      /**
       * My new app
       */
      title: string
    }
  }
}

export type TranslationFunctions = {
  home: {
    /**
     * My new app
     */
    title: () => LocalizedString
  }
  common: {
    seo: {
      /**
       * This is my new app
       */
      description: () => LocalizedString
      /**
       * My new app
       */
      title: () => LocalizedString
    }
  }
}

export type Formatters = {}
